services:
  database:
    platform: linux/amd64/v8
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: 'muzzapp'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 33306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - internal
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      LISTEN_PORT: '9000'
      MYSQL_HOST: 'database'
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: 'muzzapp'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./app:/app
    ports:
      - 9000:9000
    networks:
      - internal
networks:
  internal:
    driver: bridge